# Generated by Django 5.0.6 on 2024-06-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.CharField(max_length=300)),
                ('titulo', models.CharField(max_length=50)),
                ('descrcao', models.CharField(max_length=300)),
            ],
        ),
    ]
